### ISSUE TITLE
Python 3.6.8 no longer works with the latest updates

### ISSUE THREAD

**Issue by dwatling-sams** [microsoft/appcenter-rest-python#7]
Hi, my team has been using this dependency as part of our CD process for awhile and we noticed the newer versions broke after 2.0.2. The error:

```
  File "~/.pyenv/versions/3.6.8/lib/python3.6/site-packages/appcenter/__init__.py", line 19, in <module>
    from appcenter.tokens import AppCenterTokensClient
  File "<fstring>", line 1
    (name=)
```    
I've tracked it down to the debug statements in `tokens.py`. It appears that the newer f-string syntax of "{name=}" is not supported in 3.6.x. If possible, could those be fixed to support older versions of Python? Unfortunately, we don't have any control over the version of Python available to us.

**Comment by dalemyers** [comment]
Hmm... You are absolutely correct. I added some changes using f-strings under the assumption that this project supported 3.7 and above. Unfortunately, the fix here is likely to be dropping support for 3.6 rather than fixing this issue. 

Our testing should have caught this, but it seems that it hasn't been running for a while now. 

I'll take a look after the holidays and may get one more 3.6 compatible release out, but we will likely drop 3.6 after that and move to 3.7+.

**Comment by dalemyers** [comment]
This doesn't actually work in 3.7 either. The change has been reverted. I'm still going to be dropping 3.6 as it has other compatibility issues. Version 3.0 will be out in the next hour or so which will fix this issue overall, but it won't be backported to 3.6.

**Comment by dalemyers** [comment]
Actually, this was a 2 second fix. Version 2.1.2 is out which has this fix.
